import { Link } from 'react-router-dom'
import {
  Activity,
  ArrowRight,
  CheckCircle2,
  FolderKanban,
  FolderOpen,
  Plus,
  Search,
  Sparkles,
  type LucideIcon,
} from 'lucide-react'
import { Badge, Button, Card, CardHeader, EmptyState, PageHeader, Skeleton } from '@/components/ui'
import { useStorageQuery } from '@/hooks/useStorage'
import { storageService } from '@/storage'
import type { Project } from '@/types/project'

interface DashboardData {
  projects: Project[]
  analysisVersions: number
}

const WORKFLOW = [
  'Describe system',
  'System understanding',
  'PIECES analysis',
  'Requirements',
  'Process analysis',
  'Findings',
  'Recommendations',
  'Proposed system',
  'Diagrams',
  'Report',
]

function StatCard({ icon: Icon, label, value, hint }: { icon: LucideIcon; label: string; value: number | undefined; hint: string }) {
  return (
    <Card className="p-5">
      <div className="flex items-center gap-2 text-small text-fg-secondary">
        <Icon size={16} aria-hidden />
        {label}
      </div>
      {value === undefined ? (
        <Skeleton className="mt-3 h-8 w-12" />
      ) : (
        <p className="mt-2 text-h2 text-fg tabular-nums">{value}</p>
      )}
      <p className="mt-1 text-caption font-normal text-fg-muted">{hint}</p>
    </Card>
  )
}

export function DashboardPage() {
  const { data, loading } = useStorageQuery<DashboardData>(
    async () => {
      const [projects, stats] = await Promise.all([storageService.getProjects(), storageService.getStats()])
      return { projects, analysisVersions: stats.analysisVersions }
    },
    ['projects', 'analyses'],
  )

  const projects = data?.projects
  const recent = projects ? [...projects].sort((a, b) => b.updatedAt.localeCompare(a.updatedAt)).slice(0, 5) : []
  const hasProjects = (projects?.length ?? 0) > 0

  return (
    <>
      <PageHeader
        title="Dashboard"
        description="Analyze, document and improve any information system with structured methodology and AI assistance."
        actions={
          <Link to="/analysis/new" className="w-full sm:w-auto">
            <Button leftIcon={<Plus size={16} aria-hidden />} className="w-full justify-center" tabIndex={-1}>
              Start Analysis
            </Button>
          </Link>
        }
      />

      <section aria-label="Workspace statistics" className="grid grid-cols-2 gap-4 xl:grid-cols-4">
        <StatCard icon={FolderKanban} label="Total Projects" value={projects?.length} hint="Stored in this browser" />
        <StatCard
          icon={Activity}
          label="Active Analyses"
          value={projects?.filter((p) => p.status === 'Analyzing').length}
          hint="Projects currently analyzing"
        />
        <StatCard
          icon={CheckCircle2}
          label="Completed Analyses"
          value={projects?.filter((p) => p.status === 'Completed').length}
          hint="Projects marked completed"
        />
        <StatCard icon={Search} label="Findings" value={loading ? undefined : 0} hint="Generated by analyses" />
      </section>

      <div className="mt-8 grid gap-6 lg:grid-cols-3">
        <Card className="lg:col-span-2">
          <CardHeader
            title="Recent Projects"
            icon={<FolderOpen size={18} aria-hidden />}
            action={
              hasProjects && (
                <Link to="/projects" className="inline-flex items-center gap-1 rounded-sm text-small font-medium text-primary hover:underline">
                  View all <ArrowRight size={14} aria-hidden />
                </Link>
              )
            }
          />
          {loading ? (
            <div className="space-y-3">
              {[0, 1, 2].map((i) => (
                <Skeleton key={i} className="h-12 w-full" />
              ))}
            </div>
          ) : hasProjects ? (
            <ul className="divide-y divide-border">
              {recent.map((p) => (
                <li key={p.id} className="flex items-center justify-between gap-4 py-3">
                  <div className="min-w-0">
                    <p className="truncate font-medium text-fg">{p.name}</p>
                    <p className="truncate text-small text-fg-muted">{p.domain || 'No domain specified'}</p>
                  </div>
                  <Badge>{p.status}</Badge>
                </li>
              ))}
            </ul>
          ) : (
            <EmptyState
              icon={<FolderKanban size={22} aria-hidden />}
              title="No projects yet"
              description="Provide information about an existing or proposed system to begin your first analysis."
              action={
                <Link to="/analysis/new">
                  <Button leftIcon={<Plus size={16} aria-hidden />} className="w-full justify-center" tabIndex={-1}>
                    Start Analysis
                  </Button>
                </Link>
              }
            />
          )}
        </Card>

        <div className="space-y-6">
          <Card>
            <CardHeader title="Recent Findings" icon={<Search size={18} aria-hidden />} />
            <p className="text-small text-fg-secondary">
              Findings appear here after an analysis is completed. Each finding is linked to evidence, a PIECES
              dimension and a recommendation.
            </p>
          </Card>
          <Card className="bg-primary-soft/40">
            <CardHeader title="Recent AI Insights" icon={<Sparkles size={18} aria-hidden />} />
            <p className="text-small text-fg-secondary">
              No insights yet. SYNEX AI only reports what your system description supports and labels assumptions
              and missing information explicitly.
            </p>
          </Card>
        </div>
      </div>

      <Card className="mt-6">
        <CardHeader title="Analysis workflow" description="Every project follows the same structured path." as="h2" />
        <ol className="flex flex-wrap gap-2">
          {WORKFLOW.map((step, i) => (
            <li
              key={step}
              className="inline-flex items-center gap-2 rounded-full border border-border bg-surface-muted px-3 py-1 text-small text-fg-secondary"
            >
              <span className="flex h-5 w-5 items-center justify-center rounded-full bg-surface text-caption text-fg-muted tabular-nums">
                {i + 1}
              </span>
              {step}
            </li>
          ))}
        </ol>
      </Card>
    </>
  )
}
